// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNcvG4Tr4e9Jhu1_SK0FIz4xik-ypGsqA',
    appId: '1:855151261976:android:c7da8b009f265e6529866d',
    messagingSenderId: '855151261976',
    projectId: 'ease-scan-fyp',
    storageBucket: 'ease-scan-fyp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlos33F8a3mGe4k4tZsvOR56QOwvBFggg',
    appId: '1:855151261976:ios:8a26b73d0fe1a67529866d',
    messagingSenderId: '855151261976',
    projectId: 'ease-scan-fyp',
    storageBucket: 'ease-scan-fyp.appspot.com',
    androidClientId: '855151261976-frf58nb2kuqn4vb6h8ko9geganb5jnlb.apps.googleusercontent.com',
    iosClientId: '855151261976-ea0mqpmvev1slk6miffmigdoditf23sg.apps.googleusercontent.com',
    iosBundleId: 'com.example.easeScan',
  );

}